lunar-linux/moonbase-gnome3

- libs/webkitgtk3/BUILD
- libs/webkitgtk3/DETAILS
Similar to the one submitted by Ralter regarding qt5/glibc.
> webkitgtk3: adding a patch

- core/gnome-icon-theme-symbolic/BUILD
Florin maybe move it to /bin/true : )
> gnome-icon-theme-symbolic: fix BUILD

- core/ModemManager/DETAILS
- core/appstream-glib/DETAILS
- libs/colord-gtk/DETAILS
- libs/geoclue2/DETAILS
- libs/libmbim/DETAILS
- libs/libqmi/DETAILS
gnome3:Update some download URL to https
> gnome3:Update some download URL to https

- core/NetworkManager/DETAILS
NetworkManager:Fix Hash and download URL
> NetworkManager:Fix Hash and download URL

- libs/tracker/BUILD
- libs/tracker/DETAILS
tracker:Fix hash,download URL and BUILD
> tracker:Fix hash,download URL and BUILD 

- core/gnome-autoar/DETAILS
> gnome-autoar:Fix hash and download URL

- core/mutter/DETAILS
> mutter:Fix hash

- Cinnamon/Cinnamon/DEPENDS
> Cinnamon:fix DEPENDS of lxml

- core/gnome-bluetooth/BUILD
> gnome-bluetooth:fix a typo

- core/gnome-settings-daemon/DEPENDS
gnome-settings-daemon:fix a typo
> gnome-settings-daemon:fix a typo

- core/evolution/BUILD
- core/evolution/DEPENDS
- core/evolution/DETAILS
proposing a move from gnome/core to gnome3/core
> evolution: version bump

- core/NetworkManager/BUILD
Needed from network-manager-applet
> NetworkManager: enable build of libnm-glib

- core/NetworkManager/systemd.d/NetworkManager-dispatcher.service
- core/NetworkManager/systemd.d/NetworkManager-wait-online.service
- core/NetworkManager/systemd.d/NetworkManager.service
- core/NetworkManager/systemd.d/NetworkManager.service.d/NetworkManager-ovs.conf
Systemd related files needed for lservices
> NetworkManager: Add systemd related files

- libs/webkit2gtk3/DETAILS
> webkitgtk:up to 2.22.3

- apps/budgie-desktop/DETAILS
- apps/budgie-desktop/PRE_BUILD
budgie-desktop:add SOURCE_DIRECTORY and fix PRE_BUILD
> budgie-desktop:add SOURCE_DIRECTORY and fix PRE_BUILD

- libs/webkit2gtk3/DETAILS
webkit2gtk3:version bump to 2.22.6
> webkit2gtk3:version bump to 2.22.6

- apps/budgie-desktop/DETAILS
fix this:https://github.com/lunar-linux/moonbase-gnome3/issues/119
> budgie-desktop:fix some problem

- core/gtksourceview/DETAILS
gtksourceview-4 was required by gedit's configure
> gtksourceview: version bumped to 4.2.0

- apps/budgie-desktop/DETAILS
> budgie-desktop:fix hash

- apps/budgie-desktop/DETAILS
budgie-desktop:fix download URL
> budgie-desktop:fix download URL

- apps/budgie-desktop/DETAILS
> budgie-desktop:fix some typo

- libs/libgdata/DEPENDS
- libs/libgdata/DETAILS
Depends-On: https://github.com/lunar-linux/moonbase-gnome3/pull/161
> libgdata: version bump

- apps/polari/DEPENDS
- apps/polari/DETAILS
> polari: add to moonbase

- apps/file-roller/BUILD
- apps/file-roller/DEPENDS
- apps/file-roller/DETAILS
- apps/gnome-disk-utility/DEPENDS
- apps/gnome-disk-utility/DETAILS
version bump for 
file-roller
gnome-disks-utility
> Gnome apps

- core/nautilus/DEPENDS
- libs/libgrss/DEPENDS
- libs/libgrss/DETAILS
- libs/tracker-miners/DEPENDS
- libs/tracker-miners/DETAILS
added modules
libgrss
tracker-miners
modified modules
nautilus
> nautilus: fix crash due to missing tracker miners

- core/evolution-data-server/DETAILS
depends-on: https://github.com/lunar-linux/moonbase-other/pull/1419
> evolution-data-server: version bump

- apps/gnome-builder/BUILD
- apps/gnome-builder/DEPENDS
- apps/gnome-builder/DETAILS
- libs/jsonrpc-glib/BUILD
- libs/jsonrpc-glib/DEPENDS
- libs/jsonrpc-glib/DETAILS
- libs/template-glib/DEPENDS
- libs/template-glib/DETAILS
i select n to all optional_dependencies
> gnome-builder: initial import to moonbase.

- core/gcr/DEPENDS
- core/vala/DETAILS
added gnupg to the DEPENDS file
> Gcr - added missing dependency

- libs/webkit2gtk3/DEPENDS
> webkit2gtk3 - add missing dependency

- apps/epiphany/DEPENDS
added libhandy and libdazzle to DEPENDS
> epiphany: add dependencies

- libs/bubblewrap/DETAILS
> bubblewrap: version bump

- libs/gnome-shell-extensions/DETAILS
depends on: https://github.com/lunar-linux/moonbase-gnome3/pull/244
> gnome-shell-extensions: version bump

- core/gnome-shell/DETAILS
depends on: https://github.com/lunar-linux/moonbase-gnome3/pull/243
> gnome-shell: version bump

- apps/baobab/BUILD
- apps/baobab/DEPENDS
- apps/baobab/DETAILS
Once upon a time this was a GNOME 2.32 application. This is an update to the newest (3.38) version.
> baobab - graphical disk usage analyzer

- libs/gtk/BUILD
Disable vulkan support from gtk build.
> gtk: disable vulkan support

- libs/wpebackend-fdo/DETAILS
>  wpebackend-fdo - version bump

- core/NetworkManager/BUILD
> Network manager - fix Spelling in BUILD

- apps/budgie-desktop/DETAILS
budgie-desktop: version bumped to 10.5.3
> budgie-desktop: version bumped to 10.5.3

- libs/gexiv2/DETAILS
Works fine with exiv2 0.28.0 (https://github.com/lunar-linux/moonbase-other/pull/2523)
> gexiv2: version bumped to 0.14.2
