lunar-linux/moonbase-gnome3

- libs/libgweather/DEPENDS
Without gtk-doc can not be compiled.
> libgweather:dependent on gtk-doc

- core/nautilus/DEPENDS
gnome-autoar is a hard dependency
gexiv2 is an optional dependency
> nautilus: fix dependencies

- apps/gnome-system-monitor/BUILD
- apps/gnome-system-monitor/DEPENDS
- apps/gnome-system-monitor/DETAILS
move gnome-system-monitor from gnome/desktop/ to gnome3/apps/
> gnome-system-monitor: version bump

- apps/gedit/BUILD
The configure was exiting with this message:
+ running "default_build"
+ running "default_gnu_build"
+ running "default_config"
Missing configure and/or Makefile!
Creating /var/log/lunar/compile/gedit-3.32.2.xz 
! Problem detected during BUILD
> gedit: changed to default_meson_build

- core/mutter/BUILD
currently gnome sysprof does not supported by lunar
> mutter: disable profiler support

- apps/polari/DEPENDS
- apps/polari/PRE_BUILD
polari needs gspell and telepathy-glib as a bare minimum for compilation.
but its runtime it needs the previous modules to have gobject-introspection support.
PRE_BUILD added that checks if gspell and telepathy-glib are installed and if yes if they
have been compiled with gobject-introspection enabled, otherwise it prevents polari's
compilation
> polari: add gspell (runtime) dependency, add checks in PRE_BUILD

- core/mutter/BUILD
- core/mutter/DEPENDS
- core/mutter/DETAILS
reenable support for native backend, which is needed to start a wayland
gnome-shell from command line
> mutter: version bump

- apps/file-roller/BUILD
- apps/file-roller/DEPENDS
- apps/file-roller/DETAILS
old file-roller entry under gnome/desktop needs to be removed
> file-roller: version bump and moved under gnome3

- apps/gnome-disk-utility/DETAILS
gnome-disk-utility should be removed from other/zbeta too
> gnome-disk-utility: correct identation

- core/gnome-control-center/DETAILS
wrong update date triggers module update on every lunar renew/update
> gnome-control-center: fix update date

- core/gnome-desktop/DEPENDS
> gnome-desktop:depends libxml2

- apps/sysprof/DEPENDS
- apps/sysprof/DETAILS
currently sysprof under other/crater/ which will have to be removed and add the newest under
gnome3/apps/
> sysprof: initial import as a gnome package

- core/gobject-introspection/DEPENDS
after discussing the previous PR in more detail (see the now-closed https://github.com/lunar-linux/moonbase-gnome3/pull/229}, it's actually better to get rid of the optional_depends for python entirely.
> gobject-introspection: even better update to DEPENDS

- core/gnome-menus/DEPENDS
gnome-menus doesn't explicitly require python at all. Removed from DEPENDS.
> gnome-menus: remove unneeded dependency

- libs/gdk-pixbuf/DEPENDS
Updated dependencies, as discussed at https://github.com/lunar-linux/moonbase-gnome3/pull/233
> gdk-pixbuf pt2: update dependencies, fix typo

- core/alacarte/BUILD
- core/alacarte/DEPENDS
- core/alacarte/DETAILS
- core/alacarte/PRE_BUILD
BUILD: Removed the forced use of python2.
DEPENDS: Does not require on gnome-common, but does require python-pygobject. Removed libxslt and docbook-xsl, which are only required if documentation is installed (optional). Added docbook2X as an optional_depends.
DETAILS: Version bump, changed to GNOME download source, updated sha256sum.
PRE_BUILD: Only ran autogen.sh, unnecessary for compilation. Removed it entirely.
> alacarte pt2 (x3): changed almost everything

- libs/gdl/BUILD
- libs/gdl/DEPENDS
- libs/gdl/DETAILS
GNOME Docking Library - Provides docking features for gtk+.
Needed by inkscape >= 1.0 and darktable >= 3.0.
> GDL: GNOME Docking Library

- core/evolution/DEPENDS
Evolution has libytnef support enabled by default, and will fail to compile without it.
I've added an optional_depends to either install or disable libytnef.
> evolution: fix missing optional_depends

- core/gjs/DEPENDS
- core/gjs/DETAILS
gjs now requires mozjs78 - which I've made a separate PR for.
> gjs - version bump, mozjs dep

- apps/devhelp/DEPENDS
- apps/devhelp/DETAILS
- libs/amtk/DETAILS
devhelp needs to be removed from the gnome/ to gnome3/ repo
> Devhelp 3.38.1

- apps/gthumb/BUILD
- apps/gthumb/DEPENDS
- apps/gthumb/DETAILS
Gthumb is a feature rich image viewer that uses GTK3 and integrates well with the GNOME desktop.
- Version 3.11.1
- There is an old 2.14 in _moonbase-gnome,_ last updated in 2012.
> gthumb - new version

- libs/libdbusmenu-gtk3/BUILD
- libs/libdbusmenu-gtk3/DEPENDS
- libs/libdbusmenu-gtk3/DETAILS
- libs/libdbusmenu-gtk3/PRE_BUILD
Dbus menu passing library for gtk3. Used as an optional dep in a couple programs, including xapps and the new xfce4-panel-4.16 (coming soon!)
*Note: the PRE_BUILD file is necessary because the tar.gz doesn't have it's own containing directory, so one needs to be provided. -1:
> libdbusmenu-gtk3

- core/gnome-keyring/patch.d/ebc7bc9efacc17049e54da8d96a4a29943621113.patch
The new version of libcap breaks gnome-keyring, including libsecret. This patch fixes the problem.
> gnome-keyring - added a patchfile

- core/gcr/DEPENDS
gcr defaults to _-Dgtk_doc=true,_ which will cause the build to fail if gtk-doc isn't installed.
I've added an optional_depends to fix this.
> gcr- fix depends

- libs/webkit2gtk3/BUILD
- libs/webkit2gtk3/CONFIGURE
- libs/webkit2gtk3/DEPENDS
- libs/webkit2gtk3/DETAILS
**IMPORTANT: v2.32.0 onwards will not compile with wpebackend support enabled, until our version of wpebackend-fdo is updated (PR for that is submitted)**
BUILD:
- pointed the build to specifically use python3 ( defaults to python2 if it's installed )
-_default cmake build_ works without problems
- removed the WPEBACKEND query
CONFIGURE:
- removed the WPEBACKEND query
DEPENDS:
- removed some redundant _depends_ that are installed by other _depends_
- removed the WPEBACKEND check, changed it to an _optional depends_
DETAILS: normal version bump changes
> webkit2gtk3 - version bump, other fixes

- libs/atk/DEPENDS
the names of these optional depends were wrong, and don't actually affect the compile.
> atk - fix optional depends

- apps/caribou/DEPENDS
- apps/caribou/DETAILS
_caribou_ requires gtk2 to be explicitly disabled
- updated DEPENDS to make gtk2 optional
- change DETAILS to update modification date
> caribou : make gtk2 dependency optional

- core/gnome-desktop/DEPENDS
DEPENDS:
remove duplicate iso-codes entry
remove meson dep (installed by default)
add gobject-introspection dep (hard dep)
correct underscore vs dash on gtk-doc optional
remove unused gobject optional (hard dep)
> gnome-desktop: fix depends

- apps/epiphany/DEPENDS
- apps/epiphany/DETAILS
DETAILS: updated to 40.6 - works fine with the rest of GNOME still at 3.38.
DEPENDS: added_libportal_ to dependencies
> Epiphany: version bump, fix depends

- core/gvfs/DETAILS
Fixes the configuring error in meson build file giving this message:  
"daemon/meson.build:368:7: ERROR: Function does not take positional arguments."
> gvfs: version bump, fixes meson conf. error

- apps/gnumeric/DETAILS
- apps/gnumeric/PRE_BUILD
The sed command doesn't apply anymore, and about the itstool segfault comment there's no segfault in sight with either the itstool module nor the modules that depend on it :)
> gnumeric: version bumped to 1.12.56

- apps/eog/PRE_BUILD
I was getting this error:
```
data/meson.build:25:5: ERROR: Function does not take positional arguments.
```
> eog: fix build with newer meson

- apps/gedit/BUILD
- apps/gedit/PRE_BUILD
I was getting this error, same thing as eog:
```
data/meson.build:6:20: ERROR: Function does not take positional arguments.
```
> gedit: fix build with newer meson

- libs/gdk-pixbuf/BUILD
When starting gkrellm I was getting this error:
Error loading XPM image loader: Image type "xpm" is not supported
Cannot load xpm: (null)
gkrellm segmentation fault: (?)
According to https://github.com/Homebrew/homebrew-core/issues/169803 the loader can be re-enabled with "-Dothers=enabled", making gkrellm work again.
> gdk-pixbuf: re-enable the xpm loader

- core/gobject-introspection/DEPENDS
According to the comment in DEPENDS:
```
```
enabling cairo is recommended now, no troubles in sight currently.
> gobject-introspection: remove misleading message in DEPENDS
